name: "ReadMe Documentation Converter"
description: "Automatically generates a zip file containing the current documentation in valid format for docs.readme.com"
inputs:
  root-directory:
    description: "Root directory of the documentation"
    required: true
    default: "./"
  destination-directory:
    description: "Output directory of the generated zip file"
    required: true
    default: "./"
  zip-filename:
    description: "Name of the compressed zip file that is created by the action"
    required: true
    default: "readme_markdown.zip"
  index-name:
    description: "File name of the folder´s index files"
    required: true
    default: "index"
  version-code:
    description: "Version code of the generated documentation. This is the name of the root folder of the zip file."
    required: true
    default: "v1.0"
runs:
  using: "node12"
  main: "converter.js"